baseURL: "https://tahalahlou.dev/"
languageCode: "en-us"
title: "Personal Portfolio"
theme: "hugo-noir"
enableRobotsTXT: true

menu:
  main:
    - name: "About"
      pageRef: "/about"
      weight: 1
    - name: "Contact Me"
      pageRef: "/contact"
      weight: 5
